name: Generate Github Profile
on:
  push:
  workflow_dispatch:

jobs:
  github-profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Github Profile Repositories
        uses: ntsd/github-profile-repositories@master
        with:
          github-token: "${{ secrets.MY_GITHUB_TOKEN }}"
          template-file: "./TEMPLATE.md"
          render-file: "./README.md"
          limit: 5
      - name: Commit files
        run: |
          git config --local user.email "ntsd@users.noreply.github.com"
          git config --local user.name "ntsd"
          git add README.md 
          if ! git diff-index --quiet HEAD README.md; then
            git commit -m "docs: auto update README.md"
            git push
          fi
      - name: Pull in ntsd.dev posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://ntsd.dev/feed.xml"
