name: Generate Github Profile
on: push

jobs:
  github-profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Github Profile Repositories
        uses: ntsd/github-profile-repositories@master
        with:
          github-token: "${{ secrets.MY_GITHUB_TOKEN }}"
          template-file: "./TEMPLATE.md"
          render-file: "./README.md"
          limit: 5
      - name: Commit files
        run: |
          git config --local user.email "ntsd@users.noreply.github.com"
          git config --local user.name "ntsd"
          git add ./README.md
          git commit -am "docs: auto update README.md"
          git push
