name: Generate Github Profile
on: [push, pull_request]

jobs:
  github-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Github Profile Repositories
        uses: ntsd/github-profile-repositories
        with:
          github-token: "${{ secrets.MY_GITHUB_TOKEN }}"
          template-file: "TEMPLATE.md"
          render-file: "README.md"
      - name: Commit files
        run: |
          git commit -m "docs: auto update README.md" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
